### ISSUE TITLE
Unable to register new user

### ISSUE THREAD

**Issue by ASoldo** [jurassicjs/nuxt3-fullstack-tutorial#1]
Hi, I have cloned your repo along with mine since I'm following your youtube tutorial. When I run your app or mine it works as expected but when I use postman to register the user I get this error in the vscode terminal:
`request error] Cannot convert undefined or null to object
  at Function.entries (<anonymous>)
  at validate$1 (/C:/Users/Korisnik/Documents/nuxt3-fullstack-tutorial/.nuxt/dev/index.mjs:450:37)
  at validateUser (/C:/Users/Korisnik/Documents/nuxt3-fullstack-tutorial/.nuxt/dev/index.mjs:513:24)
  at register (/C:/Users/Korisnik/Documents/nuxt3-fullstack-tutorial/.nuxt/dev/index.mjs:632:28)
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
  at async /C:/Users/Korisnik/Documents/nuxt3-fullstack-tutorial/node_modules/h3/dist/index.mjs:420:19
  at async Server.nodeHandler (/C:/Users/Korisnik/Documents/nuxt3-fullstack-tutorial/node_modules/h3/dist/index.mjs:370:7)`

and this is the body:
`{
    "username": "myUsername", "name": "My Real Name", "email": "my.real.name@gmail.com", "password":"0123456789"
}`

Can you assist with this? Thank you.

**Comment by rohrig** [comment]
I can help you with that. If you open up the dev tools when you send the request you can open the Payload tab. There you will see what the object being sent actually looks like. 

![image](https://user-images.githubusercontent.com/45824492/180583629-093197bf-8777-4226-946d-8b86a998a642.png)

`
{data: {username: "check", name: "check", email: "check@check.com", password: "12345678"}}
`

I sent the data this way in postman and got the expected response. 

![image](https://user-images.githubusercontent.com/45824492/180583711-ad6850ce-0951-46d2-818d-2eeb18442868.png)


Let me know if that solves your problem.
